apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: customerservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customerservice
    spec:
      containers:
      - name: customerservice
        image: registry.eu-de.bluemix.net/imb_namespace/microservices:latest
        ports:
        - containerPort: 8080        
---
apiVersion: v1
kind: Service
metadata:
  name: customerservice
  labels:
    app: customerservice
spec:
  selector:
    app: customerservice
  type: NodePort
  ports:
   - protocol: TCP
     port: 8080
     nodePort: 30888
